# Remember to open the layout in the web editor to change rewards!

# Use this option if you want to enable the /addlevel command. (Useful to modify the value of the given placeholder.)
# Remember that this is not exclusive. You can use this in combination with the placeholder or as standalone without any placeholder!
use_command: true

# Use placeholders from external plugins to get the level values!
# place "none" to only use commands.
# REQUIRES: PlaceholderAPI
placeholder: 'none'
# Some example placeholders that work well with this plugin:
# (check plugin page for up-to-date list)
# TO DO

# Value that will be multiplied to the placeholder value.
# Example: if the value is set to 0.1, the placeholder will unlock a level with multipliers of 10 insted of 1
placeholder_multiplier: 1