name: LevelBoard
version: '${project.version}'
main: me.bounser.levelboard.LevelBoard
api-version: 1.13
depend: [ AdvancedGUI ]
softdepend: [ PlaceholderAPI ]
authors: [ bounser ]
description:
  AdvancedGUI Extension. Layout: LevelBoard
commands:
  addbonus: